package com.ideapipeline.orchestrator;

import com.fasterxml.jackson.databind.JsonNode;
import com.ideapipeline.client.JsonParser;
import com.ideapipeline.client.LlmClient;
import com.ideapipeline.exception.PipelineException;
import com.ideapipeline.model.CritiqueResult;
import com.ideapipeline.model.DebateMessage;
import com.ideapipeline.model.PipelineOutput;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

@Service
@Slf4j
public class CriticOrchestrator {

    private static final String CRITIC_SYSTEM_PROMPT = """
            You are a product and architecture auditor.
            You receive 3 documents generated by an AI team plus the debate history
            that produced them. Evaluate their quality, consistency and completeness
            in context of what was discussed.

            Identify:
            - critiques: specific problems or inconsistencies found
            - gaps: missing information that should be present
            - refinementNeeds: topics that need to be re-debated

            Respond ONLY in JSON with this exact format, no preamble, no markdown:
            {
              "critiques": ["critique 1", "critique 2"],
              "gaps": ["gap 1", "gap 2"],
              "refinementNeeds": ["topic 1", "topic 2"]
            }
            """;

    private final LlmClient llmClient;

    public CriticOrchestrator(LlmClient llmClient) {
        this.llmClient = llmClient;
    }

    public CritiqueResult critique(PipelineOutput docs, List<DebateMessage> debateHistory) {
        try {
            if (docs == null) {
                throw new PipelineException("docs is null", "Phase3a", 0);
            }

            validateDocument(docs.contextDocument(), "contextDocument");
            validateDocument(docs.flowDocument(), "flowDocument");
            validateDocument(docs.taskDocument(), "taskDocument");

            List<DebateMessage> safeDebateHistory = debateHistory == null ? Collections.emptyList() : debateHistory;
            log.info(
                    "Starting critique with document sizes (context={}, flow={}, task={}) and debate history size={}",
                    docs.contextDocument().length(),
                    docs.flowDocument().length(),
                    docs.taskDocument().length(),
                    safeDebateHistory.size()
            );

            String userMessage = buildUserMessage(docs, safeDebateHistory);
            String response = llmClient.chat(CRITIC_SYSTEM_PROMPT, userMessage);

            if (response == null || response.isBlank()) {
                throw new PipelineException("Empty response from critic LLM", "Phase3a", 0);
            }

            JsonNode root;
            try {
                root = JsonParser.parse(response);
            } catch (RuntimeException e) {
                log.error("Failed to parse critique JSON", e);
                throw new PipelineException("Failed to parse critique JSON", "Phase3a", 0, e);
            }

            List<String> critiques = extractArray(root, "critiques");
            List<String> gaps = extractArray(root, "gaps");
            List<String> refinementNeeds = extractArray(root, "refinementNeeds");

            log.info(
                    "Critique completed with counts: critiques={}, gaps={}, refinementNeeds={}",
                    critiques.size(),
                    gaps.size(),
                    refinementNeeds.size()
            );

            return new CritiqueResult(critiques, gaps, refinementNeeds);
        } catch (PipelineException e) {
            log.error("Critique failed", e);
            throw e;
        }
    }

    private void validateDocument(String value, String name) {
        if (value == null || value.isBlank()) {
            throw new PipelineException("document is empty: " + name, "Phase3a", 0);
        }
    }

    private String buildUserMessage(PipelineOutput docs, List<DebateMessage> debateHistory) {
        StringBuilder sb = new StringBuilder();
        sb.append("=== CONTEXT DOCUMENT ===\n");
        sb.append(docs.contextDocument()).append("\n\n");
        sb.append("=== FLOW DOCUMENT ===\n");
        sb.append(docs.flowDocument()).append("\n\n");
        sb.append("=== TASK DOCUMENT ===\n");
        sb.append(docs.taskDocument()).append("\n");

        if (!debateHistory.isEmpty()) {
            sb.append("\n=== DEBATE HISTORY ===\n");
            for (DebateMessage message : debateHistory) {
                sb.append(message.agentName())
                        .append(": ")
                        .append(message.content())
                        .append("\n");
            }
        }

        return sb.toString();
    }

    private List<String> extractArray(JsonNode root, String fieldName) {
        JsonNode node = root.get(fieldName);
        if (node == null || !node.isArray()) {
            return Collections.emptyList();
        }

        List<String> result = new ArrayList<>();
        for (JsonNode item : node) {
            result.add(item.asText());
        }
        return result;
    }
}
